pom.xml: Version bump for Atmire CUA module
Fixes this error:

java.lang.UnsupportedOperationException: Multiple update components target the same field:solr_update_time_stamp

It had been fixed in a previous version, but was re-introduced with
the fix for the issue where the CUASolrLoggerServiceImpl was caught
in an infinite loop after the DSpace 6 upgrade.